
// Objective-C API for talking to the following Go packages
//
//	github.com/divan/txqr/cmd/txqr-tester/mobile
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Txqrtester_FRAMEWORK_H__
#define __Txqrtester_FRAMEWORK_H__

#include "Txqrtester.objc.h"
#include "Universe.objc.h"

#endif
